version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: my-web
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: python:3.11-slim
    container_name: my-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "pip install -r requirements.txt && python app.py"
